### ISSUE TITLE
Failed to compile treefilter in windows

### ISSUE THREAD

**Issue by lauraset** [Megvii-BaseDetection/TreeFilter-Torch#9]
Hi, @StevenGrove . I tried to compile treefilter in windows platform, but failed.
Is it possible to provide the whl package for installing?
Thank you very much.

**Comment by StevenGrove** [comment]
I updated the code. Now it can support cuda 11 and up to pytorch 1.12.1. You can try to compile again.

**Comment by lauraset** [comment]
Hi, @StevenGrove . I still failed to complile it.
I use cuda 10.1 and pytorch 1.7.0 on the windows 10 platform.  
The 'LD_LIBRARY_PATH' does not exist. Therefore, I use the cuda_lib_path = r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64' and   cuda_lib_path = cuda_lib_path.split(':') 
However,  it shows the following messages:


49 errors detected in the compilation of "C:/Users/user1/AppData/Local/Temp/tmpxft_00003a30_00000000-10_mst.cpp1.ii".
mst.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "E:\yinxcao\tuitiantu\tttcls\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "c:\users\user1\anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '18']' returned non-zero exit status 1.


Do you know how to deal with it?
Thank you in advance.




| |
yinxcao
|
|
***@***.***
|
签名由网易邮箱大师定制
On 10/20/2022 12:39，Lin ***@***.***> wrote：

I updated the code. Now it can support cuda 11 and up to pytorch 1.12.1. You can try to compile again.

**Comment by lauraset** [comment]
@StevenGrove , Thank you very much. I have successfully compiled it in windows (torch with 1.13).
